export type Sticker = {
  id: string;
  name: string;
  src: string;
  group: "mensageiros" | "coracoes" | "glam" | "gatinho" | "fofos";
};

export const STICKERS: Sticker[] = [
  { id: "msg-pigeon", name: "Pombo", src: "/stickers/msg-pigeon.png", group: "mensageiros" },
  { id: "msg-horse", name: "Cavalo", src: "/stickers/msg-horse.png", group: "mensageiros" },
  { id: "msg-donkey", name: "Jegue", src: "/stickers/msg-donkey.png", group: "mensageiros" },
  { id: "msg-stork", name: "Cegonha", src: "/stickers/msg-stork.png", group: "mensageiros" },
  { id: "msg-swan", name: "Cisne", src: "/stickers/msg-swan.png", group: "mensageiros" },
  { id: "msg-turtle", name: "Tartaruga", src: "/stickers/msg-turtle.png", group: "mensageiros" },
  { id: "msg-plane", name: "Avião", src: "/stickers/msg-plane.png", group: "mensageiros" },
  { id: "heart", name: "Coração", src: "/stickers/heart.png", group: "coracoes" },
  { id: "heart-outline", name: "Contorno", src: "/stickers/heart-outline.png", group: "coracoes" },
  { id: "heart-sparkle", name: "Brilho", src: "/stickers/heart-sparkle.png", group: "coracoes" },
  { id: "heart-double", name: "Dois", src: "/stickers/heart-double.png", group: "coracoes" },
  { id: "heart-arrow", name: "Flecha", src: "/stickers/heart-arrow.png", group: "coracoes" },
  { id: "spark-heart", name: "Rosa", src: "/stickers/spark-heart.png", group: "coracoes" },
  { id: "kiss", name: "Beijo", src: "/stickers/kiss.png", group: "coracoes" },
  { id: "glam-crown", name: "Coroa", src: "/stickers/glam-crown.png", group: "glam" },
  { id: "glam-lipstick", name: "Batom", src: "/stickers/glam-lipstick.png", group: "glam" },
  { id: "glam-heel", name: "Salto", src: "/stickers/glam-heel.png", group: "glam" },
  { id: "glam-diamond", name: "Diamante", src: "/stickers/glam-diamond.png", group: "glam" },
  { id: "glam-star", name: "Estrela glam", src: "/stickers/glam-star.png", group: "glam" },
  { id: "glam-perfume", name: "Perfume", src: "/stickers/glam-perfume.png", group: "glam" },
  { id: "glam-bow", name: "Laço rosa", src: "/stickers/glam-bow.png", group: "glam" },
  { id: "kitty", name: "Gatinho", src: "/stickers/kitty.png", group: "gatinho" },
  { id: "kitty-bow", name: "Laço", src: "/stickers/kitty-bow.png", group: "gatinho" },
  { id: "kitty-paw", name: "Patinha", src: "/stickers/kitty-paw.png", group: "gatinho" },
  { id: "kitty-fish", name: "Peixinho", src: "/stickers/kitty-fish.png", group: "gatinho" },
  { id: "star", name: "Estrela", src: "/stickers/star.png", group: "fofos" },
  { id: "sparkle", name: "Faísca", src: "/stickers/sparkle.png", group: "fofos" },
  { id: "moon", name: "Lua", src: "/stickers/moon.png", group: "fofos" },
  { id: "cloud", name: "Nuvem", src: "/stickers/cloud.png", group: "fofos" },
  { id: "rainbow", name: "Arco-íris", src: "/stickers/rainbow.png", group: "fofos" },
  { id: "flower", name: "Flor", src: "/stickers/flower.png", group: "fofos" },
  { id: "rose", name: "Rosa", src: "/stickers/rose.png", group: "fofos" },
  { id: "daisy", name: "Margarida", src: "/stickers/daisy.png", group: "fofos" },
  { id: "bow", name: "Laço", src: "/stickers/bow.png", group: "fofos" },
  { id: "ribbon", name: "Fita", src: "/stickers/ribbon.png", group: "fofos" },
  { id: "envelope", name: "Envelope", src: "/stickers/envelope.png", group: "fofos" },
  { id: "stamp", name: "Selo", src: "/stickers/stamp.png", group: "fofos" },
  { id: "lock", name: "Cadeado", src: "/stickers/lock.png", group: "fofos" },
  { id: "key", name: "Chave", src: "/stickers/key.png", group: "fofos" },
  { id: "ring", name: "Aliança", src: "/stickers/ring.png", group: "fofos" },
  { id: "butterfly", name: "Borboleta", src: "/stickers/butterfly.png", group: "fofos" },
  { id: "bear", name: "Ursinho", src: "/stickers/bear.png", group: "fofos" },
  { id: "cupcake", name: "Cupcake", src: "/stickers/cupcake.png", group: "fofos" },
  { id: "cherry", name: "Cereja", src: "/stickers/cherry.png", group: "fofos" },
  { id: "paw", name: "Pata", src: "/stickers/paw.png", group: "fofos" },
  { id: "music", name: "Música", src: "/stickers/music.png", group: "fofos" },
  { id: "smile", name: "Sorriso", src: "/stickers/smile.png", group: "fofos" },
  { id: "star-eyes", name: "Estrelinha", src: "/stickers/star-eyes.png", group: "fofos" },
  { id: "balloon", name: "Balão", src: "/stickers/balloon.png", group: "fofos" },
  { id: "gift", name: "Presente", src: "/stickers/gift.png", group: "fofos" },
  { id: "lollipop", name: "Pirulito", src: "/stickers/lollipop.png", group: "fofos" },
  { id: "sun", name: "Sol", src: "/stickers/sun.png", group: "fofos" },
  { id: "leaf", name: "Folha", src: "/stickers/leaf.png", group: "fofos" },
  { id: "dove", name: "Pomba", src: "/stickers/dove.png", group: "fofos" },
  { id: "camera", name: "Câmera", src: "/stickers/camera.png", group: "fofos" },
];

export const STICKER_GROUPS: { id: Sticker["group"]; label: string }[] = [
  { id: "mensageiros", label: "Mensageiros" },
  { id: "coracoes", label: "Corações" },
  { id: "glam", label: "Glam" },
  { id: "gatinho", label: "Gatinho" },
  { id: "fofos", label: "Fofos" },
];
