/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as EscreverRouteImport } from './routes/escrever'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PagarRouteImport } from './routes/pagar'
import { Route as AcompanharIndexRouteImport } from './routes/acompanhar.index'
import { Route as AcompanharLetterIdRouteImport } from './routes/acompanhar.$letterId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronNoticesRouteImport } from './routes/api/cron/notices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EscreverRoute = EscreverRouteImport.update({
  id: '/escrever',
  path: '/escrever',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarRoute = PagarRouteImport.update({
  id: '/pagar',
  path: '/pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharIndexRoute = AcompanharIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcompanharRoute,
} as any)
const AcompanharLetterIdRoute = AcompanharLetterIdRouteImport.update({
  id: '/$letterId',
  path: '/$letterId',
  getParentRoute: () => AcompanharRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNoticesRoute = ApiCronNoticesRouteImport.update({
  id: '/api/cron/notices',
  path: '/api/cron/notices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRouteWithChildren
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/escrever': typeof EscreverRoute
  '/login': typeof LoginRoute
  '/pagar': typeof PagarRoute
  '/acompanhar/$letterId': typeof AcompanharLetterIdRoute
  '/acompanhar/': typeof AcompanharIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/notices': typeof ApiCronNoticesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/escrever': typeof EscreverRoute
  '/login': typeof LoginRoute
  '/pagar': typeof PagarRoute
  '/acompanhar/$letterId': typeof AcompanharLetterIdRoute
  '/acompanhar': typeof AcompanharIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/notices': typeof ApiCronNoticesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acompanhar': typeof AcompanharRouteWithChildren
  '/admin': typeof AdminRoute
  '/conta': typeof ContaRoute
  '/escrever': typeof EscreverRoute
  '/login': typeof LoginRoute
  '/pagar': typeof PagarRoute
  '/acompanhar/$letterId': typeof AcompanharLetterIdRoute
  '/acompanhar/': typeof AcompanharIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/notices': typeof ApiCronNoticesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acompanhar'
    | '/admin'
    | '/conta'
    | '/escrever'
    | '/login'
    | '/pagar'
    | '/acompanhar/$letterId'
    | '/acompanhar/'
    | '/api/auth/$'
    | '/api/cron/notices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/conta'
    | '/escrever'
    | '/login'
    | '/pagar'
    | '/acompanhar/$letterId'
    | '/acompanhar'
    | '/api/auth/$'
    | '/api/cron/notices'
  id:
    | '__root__'
    | '/'
    | '/acompanhar'
    | '/admin'
    | '/conta'
    | '/escrever'
    | '/login'
    | '/pagar'
    | '/acompanhar/$letterId'
    | '/acompanhar/'
    | '/api/auth/$'
    | '/api/cron/notices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcompanharRoute: typeof AcompanharRouteWithChildren
  AdminRoute: typeof AdminRoute
  ContaRoute: typeof ContaRoute
  EscreverRoute: typeof EscreverRoute
  LoginRoute: typeof LoginRoute
  PagarRoute: typeof PagarRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronNoticesRoute: typeof ApiCronNoticesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrever': {
      id: '/escrever'
      path: '/escrever'
      fullPath: '/escrever'
      preLoaderRoute: typeof EscreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar': {
      id: '/pagar'
      path: '/pagar'
      fullPath: '/pagar'
      preLoaderRoute: typeof PagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar/': {
      id: '/acompanhar/'
      path: '/'
      fullPath: '/acompanhar/'
      preLoaderRoute: typeof AcompanharIndexRouteImport
      parentRoute: typeof AcompanharRoute
    }
    '/acompanhar/$letterId': {
      id: '/acompanhar/$letterId'
      path: '/$letterId'
      fullPath: '/acompanhar/$letterId'
      preLoaderRoute: typeof AcompanharLetterIdRouteImport
      parentRoute: typeof AcompanharRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/notices': {
      id: '/api/cron/notices'
      path: '/api/cron/notices'
      fullPath: '/api/cron/notices'
      preLoaderRoute: typeof ApiCronNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcompanharRouteChildren {
  AcompanharLetterIdRoute: typeof AcompanharLetterIdRoute
  AcompanharIndexRoute: typeof AcompanharIndexRoute
}

const AcompanharRouteChildren: AcompanharRouteChildren = {
  AcompanharLetterIdRoute: AcompanharLetterIdRoute,
  AcompanharIndexRoute: AcompanharIndexRoute,
}

const AcompanharRouteWithChildren = AcompanharRoute._addFileChildren(
  AcompanharRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcompanharRoute: AcompanharRouteWithChildren,
  AdminRoute: AdminRoute,
  ContaRoute: ContaRoute,
  EscreverRoute: EscreverRoute,
  LoginRoute: LoginRoute,
  PagarRoute: PagarRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronNoticesRoute: ApiCronNoticesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
